
name: 'P21_Analytics_Engineering'
version: '1.0.0'
config-version: 2

profile: 'p21_server_connect' 
# Ensure this profile exists in the profiles.yml file in the configuration folder. The configuration folder can be viewed by running `dbt debug --config-dir`

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  P21_Analytics_Engineering:
    materialized: view
