WITH result as (
    SELECT [company_id]
        ,[location_id]
        ,[default_branch_id]
        -- ,[delete_flag]
        ,[date_created]
        ,[date_last_modified]
        ,[last_maintained_by]
        -- ,[shipping_group_id]
        -- ,[tax_group_id]
        ,[location_name]
        -- ,[lot_bin_integration]
        -- ,[location_type]
        -- ,[no_of_periods_to_supply]
        -- ,[available_to_transfer_calc_cd]
        -- ,[use_tags_flag]
        -- ,[tag_prefix]
        -- ,[rf_enabled_flag]
        -- ,[fedex_loc_acct_no]
        -- ,[fedex_meter_no]
        -- ,[dea_code]
        -- ,[dea_number]
        -- ,[wwms_show_bin_alloc_warning]
        -- ,[parker_distributor_no]
        -- ,[rf_frontcounterpicking_flag]
        -- ,[default_oe_source_loc_id]
        -- ,[region_uid]
        -- ,[consigned_ship_to_id]
        -- ,[po_receipts_bin_uid]
        -- ,[transfer_receipts_bin_uid]
        -- ,[autoconfirm_prod_pick_ticket]
        -- ,[print_prod_pick_ticket]
        -- ,[ups_account_no]
        -- ,[ups_pickup_type_cd]
        -- ,[ups_customer_type_cd]
        -- ,[general_manager_salesrep_id]
        -- ,[inv_group_hdr_uid]
        -- ,[default_fax_cover_uid]
        -- ,[associated_location_id]
        -- ,[ups_olt_access_key]
        -- ,[ups_olt_password]
        -- ,[ups_olt_user_id]
        -- ,[strategic_retail_location_flag]
        -- ,[roadnet_do_not_route_flag]
        -- ,[aia_prompt_flag]
        -- ,[cardlock_acct_no]
        -- ,[pedigree_contact_id]
        -- ,[wwms_default_primary_bin_po]
        -- ,[wwms_default_primary_bin_trans]
        -- ,[manufacturer_rebate_loc]
        -- ,[track_customer_package_flag]
        -- ,[weight_per_box]
        -- ,[nonstock_available_to_transfer]
        -- ,[nonstock_no_periods_to_supply]
        -- ,[distribution_center]
        -- ,[server_time_zone_offset]
        -- ,[sales_tax_payable_gl_account]
        -- ,[external_tax_backup_percent]
        -- ,[region_flag]
        -- ,[use_bins_for_trans_schedule_flag]
        -- ,[use_pallets_flag]
        -- ,[use_pallet_types_flag]
        -- ,[voucher_class]
        -- ,[allow_multiple_assemblies_flag]
        -- ,[undershipment_allocation_flag]
        -- ,[ratelinx_location_id]
        -- ,[centeron_default_taker]
        -- ,[start_pick_seq_tag_bulk]
        -- ,[high_velocity_level]
        -- ,[mid_velocity_level]
        -- ,[tax_by_source_loc_flag]
        -- ,[shipping_location_flag]
        -- ,[gst_registration_no]
        -- ,[wwms_default_deposit_bin]
        -- ,[quotebuilder_default_taker]
        -- ,[exclude_otf_items_flag]
        -- ,[ext_tax_company_code]
        -- ,[fca_bin_uid]
        -- ,[fca_reason_id]
        -- ,[prevent_auto_assign_lots_flag]
        -- ,[fedex_label_size_cd]
        -- ,[fedex_label_orientation_cd]
        -- ,[fedex_label_format_cd]
        -- ,[prevent_auto_ts_creation_flag]
        -- ,[tr_receipts_use_primary_bin_cd]
        -- ,[damaged_bin_uid]
        -- ,[nostock_bin_uid]
        -- ,[consignment_customer_id]
        -- ,[print_packinglist_in_wwms]
        -- ,[print_transfer_packinglist_in_wwms]
        -- ,[rollup_location_id]
        -- ,[pick_problem_bin_uid]
        -- ,[rf_transfer_pack_list_printer]
        -- ,[print_ucc128_with_pt_flag]
        -- ,[auto_allocate_in_po_import_flag]
        -- ,[default_field_destroy_bin_uid]
        -- ,[default_field_destroy_reason_id]
        -- ,[warranty_return_inv_mast_uid]
        -- ,[warranty_return_bin_uid]
        -- ,[use_dq_routing_flag]
        -- ,[use_catch_weight_processing_flag]
        -- ,[rma_receipts_use_primary_bin]
        -- ,[fedex_default_phone_number]
        -- ,[skip_parker_export_in_oe]
        -- ,[adjust_found_items_flag]
        -- ,[damaged_flag]
        -- ,[cardlock_nexus_location]
        -- ,[fedex_smartpost_hub_cd]
        -- ,[datagate_supplier_no]
        -- ,[datagate_inv_seq_no]
        -- ,[datagate_sales_seq_no]
        -- ,[rma_default_warranty_bin_uid]
        -- ,[ext_tax_freight_bkup_tax_exempt]
        -- ,[sporadic_item_threshold_periods]
        -- ,[rfnavigator_url]
        -- ,[rfnavigator_user_name]
        -- ,[rfnavigator_password]
        -- ,[trackabout_location_tid]
        -- ,[priority_location_id]
        -- ,[update_velocity_settings]
        -- ,[rfnavigator_drop_location]
        -- ,[rfnavigator_start_unit_no]
    FROM {{ ref('src_locations')}} as l
    WHERE delete_flag <> 'Y'
)

select * from result