with result AS (
SELECT 
--# Location properties 
      [location_id] 
       ,[inv_mast_uid] 
       ,[stockable] 
       ,[sellable] 
       ,[buy] 
       ,[make] 
       ,[requisition] 
       ,[discontinued]
-- [purchase_discount_group]
-- [sales_discount_group] 
       ,[delete_flag] 
       ,[date_created] 
       ,[date_last_modified] 
       ,[last_maintained_by] 
       ,[no_charge]
--# Inventory properties 
       ,[track_bins] 
       ,[primary_bin]
--# Inventory quantities 
       ,[qty_on_hand] 
       ,[qty_in_process] 
       ,[qty_allocated] 
       ,[qty_backordered] 
       ,[qty_in_transit]
--# Accounting 
       ,[product_group_id] 
       ,[gl_account_no] 
       ,[revenue_account_no] 
       ,[cos_account_no] 
       ,[ta_rental_revenue_account_no] 
       ,[rma_revenue_account_no] 
       ,[moving_average_cost] 
       ,[standard_cost] 
       ,[tax_group_id] 
       ,[ta_rental_tax_group_id]
--# Replenishment 
       ,[replenishment_method] 
       ,[order_quantity] 
       ,[inv_min] 
       ,[inv_max] 
       ,[safety_stock] 
       ,[min_replenishment_qty] 
       ,[replenishment_location] 
       ,[average_monthly_usage] 
       ,[safety_stock_type] 
       ,[service_level_measure] 
       ,[service_level_pct_goal]
--# Purchasing 
       ,[primary_supplier_id]
--# Price Sources 
       ,[price1] 
       ,[price2] 
       ,[price3] 
       ,[price4] 
       ,[price5] 
       ,[price6] 
       ,[price7] 
       ,[price8] 
       ,[price9] 
       ,[price10]
--# Misc 
       ,[add_to_cycle_count]
--# Dynamic dates 
       ,[last_sale_date] 
       ,[last_purchase_date] 
       ,[inv_last_changed_date]
       ,[date_last_counted] 
-- [purchase_class] 
-- [cycle_counting_category] 
-- [company_id] 
-- [last_rec_po] 
-- [last_rec_po_with_disc] 
-- [purch_or_transfer] 
-- [next_due_in_po_cost] 
-- [next_due_in_po_date] 
-- [protected_stock_qty] 
-- [months_in_season] 
-- [default_in_oe] 
-- [period_first_stocked] 
-- [year_first_stocked] 
-- [usage_lock] 
-- [usage_lock_period] 
-- [usage_lock_year] 
-- [qty_reserved_due_in] 
-- [deadstock_flag] 
-- [lot_bin_integration] 
-- [default_shipment]
-- [on_obt_flag]
-- [on_release_schedule_flag]
-- [on_backorder_flag]
-- [created_by]
-- [periods_to_supply_min]
-- [periods_to_supply_max]
-- [putaway_rank]
-- [iva_taxable_flag]
-- [item_putaway_attribute_uid]
-- [splittable_flag]
-- [allow_ds_discontinued_items]
-- [allow_sp_discontinued_items]
-- [demand_pattern_cd]
-- [demand_pattern_evaluation_date]
-- [demand_forecast_formula_uid]
-- [pattern_manually_edited_flag]
-- [demand_pattern_behavior_cd]
-- [pattern_like_inv_mast_uid]
-- [pattern_like_location_id]
-- [behaves_like_lock_flag]
-- [behaves_like_lock_period]
-- [behaves_like_lock_year]
-- [landed_cost_account_no]
-- [price_family_uid]
-- [default_selling_unit]
-- [cardlock_product_id]
-- [loc_item_type_cd]
-- [loc_cust_parent_inv_mast_uid]
-- [main_bulk_location_flag]
-- [dflt_source_loc_flag]
-- [cycle_count_flag]
-- [promotional_flag]
-- [future_standard_cost]
-- [effective_date]
-- [assembly_prompt_option]
-- [restricted_flag]
-- [drp_item_flag]
-- [saved_demand_forecast_formula_uid]
-- [demand_formula_computed_year_period]
-- [demand_pattern_computed_year_period]
-- [year_period_last_forecast]
-- [vendor_rebate_account_no]
-- [transfer_usage_percent]
-- [manufacturer_req_stock_flag]
-- [fc_bin]
-- [pumpoff_item]
-- [pumpoff_uom]
-- [on_future_order_flag]
-- [on_future_prod_order_flag]
-- [max_liability]
-- [max_transfer_qty]
-- [alt_tax_group_id]
-- [returnable_flag]
-- [iqs_item_flag]
-- [slab_track_bins_flag]
-- [edi_832_discontinued_sent_flag]
-- [buyer_id]
-- [cycle_count_no]
-- [cycle_count_qty]
-- [transfer_conversion_uom]
-- [ecc_enabled_flag]
-- [inv_mast_uid_dup_usage]
-- [transfer_order_point]
-- [transfer_order_qty]
-- [critical_item_flag]
-- [deviation_lookback_pds]
-- [deviation_mult_one_pd]
-- [deviation_mult_two_pd]
-- [deviation_mult_three_pd]
-- [min_safety_stock_days]
-- [max_safety_stock_days]
-- [crit_item_deviation_mult]
-- [crit_min_safety_stock_days]
-- [crit_max_safety_stock_days]
-- [osmi_item_flag]
-- [local_item_flag]
FROM {{ ref ('src_inv_loc' )}}
WHERE delete_flag <> 'Y' ) 


SELECT  * FROM result