with result AS (
SELECT  il.[inv_mast_uid] 
       ,il.[item_id] 
       ,il.[item_desc] 
       ,il.[extended_desc] 
       ,il.[inactive] 
       ,il.[upc_or_ean] 
       ,il.[serialized]
       ,il.[catalog_item] 
       ,il.[short_code] 
       ,il.[track_lots] 
       ,il.[requisition] 
       ,il.[default_product_group] 
       ,il.[other_charge_item] 
       ,il.[base_unit] 
       ,il.[sales_pricing_unit] 
       ,il.[sales_pricing_unit_size] 
       ,il.[purchase_pricing_unit] 
       ,il.[purchase_pricing_unit_size] 
       ,il.[default_selling_unit] 
       ,il.[update_via_pricing_service] 
       ,il.[default_purchasing_unit] 
       ,il.[convert_quantities] 
       ,il.[haz_mat_flag] 
       ,cd.[code_description] as [item_type_description] 
       ,il.[cylinder_item_flag] 
       ,il.[rental_item_flag] 
       ,il.[ecc_enabled_flag] 
       ,il.[date_created] 
       ,il.[created_by] 
       ,il.[date_last_modified] 
       ,il.[last_maintained_by] 

       -- ,il.[weight] 
       -- ,il.[net_weight] 
       -- ,il.[cube] 
       -- ,il.[date_inactive] 
       -- ,il.[date_reactive] 
       -- ,il.[catch_weight_indicator] 
       -- ,il.[purchasing_weight] 
       -- ,il.[class_id1] 
       -- ,il.[class_id2] 
       -- ,il.[class_id3] 
       -- ,il.[class_id4] 
       -- ,il.[class_id5] 
       -- ,il.[upc_or_ean_id] 
       -- ,il.[product_type] 
       -- ,il.[hose] 
       -- ,il.[fitting] 
       -- ,il.[d_length] 
       -- ,il.[price1] 
       -- ,il.[price2] 
       -- ,il.[price3] 
       -- ,il.[price4] 
       -- ,il.[price5] 
       -- ,il.[price6] 
       -- ,il.[price7] 
       -- ,il.[price8] 
       -- ,il.[price9] 
       -- ,il.[price10] 
       -- ,il.[default_sales_discount_group] 
       -- ,il.[default_purchase_disc_group] 
       -- ,il.[commission_class_id] 
       -- ,il.[invoice_type] 
       -- ,il.[pick_ticket_type] 
       -- ,il.[hi] 
       -- ,il.[ti] 
       -- ,il.[class_code] 
       -- ,il.[item_terms_discount_pct] 
       -- ,il.[tpcx_status] 
       -- ,il.[default_transfer_unit] 
       -- ,il.[keywords] 
       -- ,il.[fulltext_timestamp] 
       -- ,il.[vendor_consigned] 
       -- ,il.[disposition] 
       -- ,il.[source_type_cd] 
       -- ,il.[use_tags_flag] 
       -- ,il.[tag_hold_class_uid] 
       -- ,il.[shippable_unit_flag] 
       -- ,il.[auto_allocation_flag] 
       -- ,il.[currency_id] 
       -- ,il.[iva_taxable_flag] 
       -- ,il.[restricted_flag] 
       -- ,il.[parker_product_cd] 
       -- ,il.[parker_division_cd] 
       -- ,il.[service_terms_discount_pct] 
       -- ,il.[service_commission_class_id] 
       -- ,il.[override_specific_costing] 
       -- ,il.[sold_outside_us_flag] 
       -- ,il.[configurable_flag] 
       -- ,il.[last_pricing_service_date] 
       -- ,il.[commodity_code] 
       -- ,il.[default_price_family_uid] 
       -- ,il.[spa_item_flag] 
       -- ,il.[unspsc_code] 
       -- ,il.[dci_code] 
       -- ,il.[epa_cert_req_flag] 
       -- ,il.[aia_enabled_flag] 
       -- ,il.[aia_remnant_qty] 
       -- ,il.[length] 
       -- ,il.[width] 
       -- ,il.[height] 
       -- ,il.[avail_for_sch_delivery_flag] 
       -- ,il.[cust_parent_inv_mast_uid] 
       -- ,il.[manufacturer_program_type_uid] 
       -- ,il.[manufacturer_program_type_pct] 
       -- ,il.[use_revisions_flag] 
       -- ,il.[use_oc_tax_rules_flag] 
       -- ,il.[tally_flag] 
       -- ,il.[oc_print_on_pick_ticket_flag] 
       -- ,il.[oc_print_on_invoice_flag] 
       -- ,il.[single_use_or_reusable] 
       -- ,il.[unitconv_override_oe_flag] 
       -- ,il.[unitconv_override_purc_flag] 
       -- ,il.[item_sales_tax_class] 
       -- ,il.[lifo_pool_item_class] 
       -- ,il.[country_of_origin_req_flag] 
       -- ,il.[nmfc_hdr_uid] 
       -- ,il.[catch_lot_weight_flag] 
       -- ,il.[ucc128_pack_type_cd] 
       -- ,il.[ucc128_standard_pack_size] 
       -- ,il.[redemption_item_flag] 
       -- ,il.[redemption_value] 
       -- ,il.[bo_fill_canadian_purchase_flag] 
       -- ,il.[country_of_origin_code] 
       -- ,il.[apply_state_fuel_surcharge_flag] 
       -- ,il.[type_of_sale] 
       -- ,il.[commission_cost_multiplier] 
       -- ,il.[item_label_type_cd] 
       -- ,il.[drum_pickup_flag] 
       -- ,il.[item_notes] 
       -- ,il.[retail_accessories] 
       -- ,il.[hazmat_ormd_flag] 
       -- ,il.[hazmat_ormd_qty] 
       -- ,il.[functional_class] 
       -- ,il.[sales_set_quantity] 
       -- ,il.[suppress_from_web_flag] 
       -- ,il.[vndr_stock] 
       -- ,il.[ptlx_stock] 
       -- ,il.[pf_stock] 
       -- ,il.[round_prices] 
       -- ,il.[pumpoff_item] 
       -- ,il.[pumpoff_uom] 
       -- ,il.[conoco_division_class_id] 
       -- ,il.[buy_get_class] 
       -- ,il.[discontinued_date] 
       -- ,il.[label_group_item_flag] 
       -- ,il.[core_item_flag] 
       -- ,il.[generic_item_desc] 
       -- ,il.[allow_custom_desc_flag] 
       -- ,il.[manufacturer_name] 
       -- ,il.[brand_name] 
       -- ,il.[part_number] 
       -- ,il.[do_not_auto_allocate_desc] 
       -- ,il.[exclude_order_level_discount_flag] 
       -- ,il.[sample_item_flag] 
       -- ,il.[sample_inv_mast_uid] 
       -- ,il.[core_parent_item_id] 
       -- ,il.[attribute_group_uid] 
       -- ,il.[partner_program_labor_item_flag] 
       -- ,il.[brand_type] 
       -- ,il.[iqs_item_flag] 
       -- ,il.[import_as_direct_ship_flag] 
       -- ,il.[do_not_field_destroy_flag] 
       -- ,il.[inv_mast_uid_dup_usage] 
       -- ,il.[rolled_item_flag] 
       -- ,il.[exclude_from_edi832_flag] 
       -- ,il.[order_hold_class_id] 
       -- ,il.[default_direct_ship_disp_flag] 
       -- ,il.[buyer_id] 
       -- ,il.[packing_weight_tracking_option] 
       -- ,il.[tariff_surcharge_pct] 
       -- ,il.[tariff_surcharge_inv_mast_uid] 
       -- ,il.[exclude_from_auto_short_buy_flag] 
       -- ,il.[item_classification_id] 
       -- ,il.[hazmat_fee_inv_mast_uid] 
       -- ,il.[bol_class] 
       -- ,il.[rental_item_uid] 
       -- ,il.[dflt_dimension_scale] 
       -- ,il.[local_item_flag]
FROM {{ ref('src_inv_mast')}} as il
LEFT JOIN {{ ref('src_code')}} as cd on il.[item_type_cd] = cd.[code_no]

)


SELECT  * FROM result