with result as 
(
SELECT [company_id]
      ,[product_group_id]
      ,[product_group_desc]
      ,[asset_account_no]
      ,[revenue_account_no]
      ,[cos_account_no]
      ,[delete_flag]
      ,[date_created]
      ,[date_last_modified]
      ,[last_maintained_by]
    --   ,[parker_product_code]
    --   ,[tax_group_id]
    --   ,[completion_lead_time]
    --   ,[required_lead_time]
    --   ,[product_group_uid]
    --   ,[landed_cost_account_no]
    --   ,[environmental_fee_flag]
    --   ,[admin_fee_flag]
    --   ,[include_in_size_analysis_flag]
    --   ,[rma_revenue_account_no]
    --   ,[price_rounding_flag]
    --   ,[price_rounding_threshold]
    --   ,[apply_min_margin_rules_flag]
    --   ,[vendor_rebate_account_no]
    --   ,[enable_line_profit_warning]
    --   ,[minimum_order_line_profit]
    --   ,[maximum_order_line_profit]
    --   ,[oe_skip_profit_check_unpriced]
    --   ,[oe_skip_profit_check_uncosted]
    --   ,[compressor_flag]
    --   ,[cardlock_product_group_type_cd]
    --   ,[ta_rental_revenue_account_no]
    --   ,[percent_req_to_alloc_transfer]
    --   ,[future_effective_date]
    --   ,[future_price_rounding_threshold]
  FROM {{ref('src_product_group')}}
  WHERE delete_flag <> 'Y'
  )

  SELECT * FROM result